name: Repository Traffic Tracker

on:
  schedule:
    
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Track Repository Traffic
        uses: sangonikola/repository-traffic-action@v0.1.6
        env:
          TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
