name: Repository Traffic Tracker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Track Repository Traffic
        uses: techknowlogick/traffic-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
